name: slack-notification

on: [pull_request]

jobs:
  slack-notifications:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a pull request is made
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.xoxe.xoxp-1-Mi0yLTMyOTg4OTU0NDI2NDItMzMxMTUwOTQ3NTA0MS0zNTM3NzUyNjcxMDI2LTM1MzQ4NTY1OTE2NjktYzc3ODhjZTNhNTNlYWQzMDA1YTA3NGI3ZDY4YWM0ZjU4MzU4ZWZiOWNmNDVmODViYjRhODMzZWNjOGRmNzJjMQ }}
          slack-channel: D038SS5C47M
          slack-text: Hello! New pull request "${{ github.event_name }}" in "${{ github.repository }}" 🤓
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
